### ISSUE TITLE
Not able to generate appx using manifoldjs

### ISSUE THREAD

**Issue by madhuramehendalewhatfix** [MicrosoftDocs/edge-developer#1107]
Followed the steps mentioned here to package extension for edge legacy-
[](https://docs.microsoft.com/en-us/microsoft-edge/edgehtml/extensions/guides/packaging/using-manifoldjs-to-package-extensions)

But while executing the last command - **manifoldjs -l debug -p edgeextension package <EXTENSION NAME>\edgeextension\manifest\** I am getting this error-

_Failed to package the Microsoft Edge Extension Platform app.
                          at /home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/manifoldjs-lib/lib/projectBuilder.js:140:29
                          at _rejected (/home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/q/q.js:864:24)
                          at /home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/q/q.js:890:30
                          at Promise.when (/home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/q/q.js:1142:31)
                          at Promise.promise.promiseDispatch (/home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/q/q.js:808:41)
                          at /home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/q/q.js:624:44
                          at runSingle (/home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/q/q.js:137:13)
                          at flush (/home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/q/q.js:125:13)
                          at processTicksAndRejections (internal/process/next_tick.js:74:9)
                      Failed to create the package. The CloudAppX service returned an error - Site Disabled (403): ï»¿<!DOCTYPE html>
                      <html>
                      <head>
                          <title>Web App - Unavailable</title>
                          <style type="text/css">
                              html {
                                  height: 100%;
                                  width: 100%;
                              }
                      
                              #feature {
                                  width: 960px;
                                  margin: 95px auto 0 auto;
                                  overflow: auto;
                              }
                      
                              #content {
                                  font-family: "Segoe UI";
                                  font-weight: normal;
                                  font-size: 22px;
                                  color: #ffffff;
                                  float: left;
                                  width: 460px;
                                  margin-top: 68px;
                                  margin-left: 0px;
                                  vertical-align: middle;
                              }
                      
                                  #content h1 {
                                      font-family: "Segoe UI Light";
                                      color: #ffffff;
                                      font-weight: normal;
                                      font-size: 60px;
                                      line-height: 48pt;
                                      width: 800px;
                                  }
                      
                              p a, p a:visited, p a:active, p a:hover {
                                  color: #ffffff;
                              }
                      
                              #content a.button {
                                  background: #0DBCF2;
                                  border: 1px solid #FFFFFF;
                                  color: #FFFFFF;
                                  display: inline-block;
                                  font-family: Segoe UI;
                                  font-size: 24px;
                                  line-height: 46px;
                                  margin-top: 10px;
                                  padding: 0 15px 3px;
                                  text-decoration: none;
                              }
                      
                                  #content a.button img {
                                      float: right;
                                      padding: 10px 0 0 15px;
                                  }
                      
                                  #content a.button:hover {
                                      background: #1C75BC;
                                  }
                          </style>
                      </head>
                      <body bgcolor="#00abec">
                          <div id="feature">
                                  <div id="content">
                                      <h1 id="unavailable">Error 403 - This web app is stopped.</h1>
                                      <p id="tryAgain">The web app you have attempted to reach is currently stopped and does not accept any requests. Please try to reload the page or visit it again soon.</p>
                                      <p id="toAdmin">If you are the web app administrator, please find the common 403 error scenarios and resolution <a href="https://go.microsoft.com/fwlink/?linkid=2095007" target="_blank">here</a>. For further troubleshooting tools and recommendations, please visit <a href="https://portal.azure.com/">Azure Portal</a>.</p>
                              </div>
                          </div>
                      </body>
                      </html>
                      
                          at Request._callback (/home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/manifoldjs-edgeextension/lib/appPackage.js:72:32)
                          at Request.self.callback (/home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/request/request.js:185:22)
                          at Request.emit (events.js:197:13)
                          at Request.<anonymous> (/home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/request/request.js:1154:10)
                          at Request.emit (events.js:197:13)
                          at IncomingMessage.<anonymous> (/home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/request/request.js:1076:12)
                          at Object.onceWrapper (events.js:285:13)
                          at IncomingMessage.emit (events.js:202:15)
                          at endReadableNT (_stream_readable.js:1129:12)
                          at processTicksAndRejections (internal/process/next_tick.js:76:17)
[error] manifoldjs  : One or more platforms could not be generated successfully.
                          at /home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/manifoldjs-lib/lib/projectBuilder.js:28:23
                          at _fulfilled (/home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/q/q.js:854:54)
                          at /home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/q/q.js:883:30
                          at Promise.promise.promiseDispatch (/home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/q/q.js:816:13)
                          at /home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/q/q.js:624:44
                          at runSingle (/home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/q/q.js:137:13)
                          at flush (/home/madhura/.nvm/versions/node/v11.10.0/lib/node_modules/manifoldjs/node_modules/q/q.js:125:13)
                          at processTicksAndRejections (internal/process/next_tick.js:74:9)_

Let me know if you need any more details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25297bc3-b359-a4db-bc6b-25a89cea8b8d
* Version Independent ID: 994f8c6d-e79b-a0e8-4d32-82c041fe99bf
* Content: [Using ManifoldJS to package extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/edgehtml/extensions/guides/packaging/using-manifoldjs-to-package-extensions)
* Content Source: [microsoft-edge/edgehtml/extensions/guides/packaging/using-manifoldjs-to-package-extensions.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/edgehtml/extensions/guides/packaging/using-manifoldjs-to-package-extensions.md)
* Product: **microsoft-edge**
* Technology: ****
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @madhuramehendalewhatfix, sorry to hear about this issue. You can contact the extensions team for support using any of the methods listed here: https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-us
I'll go ahead and close this issue now. Thanks.
