### ISSUE TITLE
Fail to use python to auto test on edge based on selenium 4 

### ISSUE THREAD

**Issue by brucezlata** [MicrosoftDocs/edge-developer#1465]
Below code is not working.
Python39
Selenium 4.0.0.rc1

```
from selenium import __version__
from selenium import webdriver
from selenium.webdriver.edge.options import Options
from selenium.webdriver.edge.service import Service

print(__version__)

options = Options()
options.headless = False
options.use_chromium = True

edge_service = Service("D:\\bin\\edgedriver_win64\\msedgedriver.exe")

browser = webdriver.Edge(
   service=edge_service,
   options= options)

browser.get('https://dev.to')

print(browser.title)
browser.close()
```

selenium $ & C:/Python39/python.exe d:/exp/projects/selenium/edge_selenium4.py
4.0.0.rc1

DevTools listening on ws://127.0.0.1:64176/devtools/browser/dbae61be-9480-41eb-91fc-83215c97adcd
[33740:22172:0918/142135.005:ERROR:dual_engine_service_win.cc(1094)] Unable to parse SiteList: Data Decoder terminated unexpectedly
Traceback (most recent call last):
  File "d:\exp\projects\selenium\edge_selenium4.py", line 17, in <module>
    browser = webdriver.Edge(
  File "C:\Python39\lib\site-packages\selenium\webdriver\edge\webdriver.py", line 62, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.EDGE['browserName'], "ms",
  File "C:\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 265, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 356, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 417, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from tab crashed
  (Session info: MicrosoftEdge=93.0.961.47)
Stacktrace:
Backtrace:
        Ordinal0 [0x00007FF6D0B392E2+4821730]
        Ordinal0 [0x00007FF6D07BD3E3+1168355]
        Ordinal0 [0x00007FF6D07ABC35+1096757]
        Ordinal0 [0x00007FF6D07AA0A2+1089698]
        Ordinal0 [0x00007FF6D07AA750+1091408]
        Ordinal0 [0x00007FF6D07B6BAC+1141676]
        Ordinal0 [0x00007FF6D07A9A7F+1088127]

![image](https://user-images.githubusercontent.com/21032579/133878603-acf88006-718d-4341-b3dc-01762868d8ab.png)

**Comment by brucezlata** [comment]
Microsoft Edge
Version 93.0.961.47 (Official build) (64-bit)

**Comment by Reezaali** [comment]
Hi @brucezlata , sorry to hear that you're getting an error. The best way to get support on this issue is to use the feedback tool in Microsoft Edge. Can you send feedback within Edge as follows?

Choose **...** > **Help and feedback** > **Send feedback**. 

If you include your email address, they can reach out to you directly.
