### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by tmnoonan** [MicrosoftDocs/edge-developer#165]
This command does not work.  It worked last time I packaged the app (Feb 2017) but it does not work anymore, I even tried packaging the exact same files.  Here's the output:

C:\Users\tmnoo\Desktop&gt;manifoldjs -l debug -p edgeextension package [APPNAME]\edgeextension\manifest\
[debug] manifoldjs  : Loading platform module: manifoldjs-edgeextension
[debug] manifoldjs  : Packaging the 'Microsoft Edge Extension Platform' app...
[info ] edgeextension: Packaging the Microsoft Edge Extension Platform app...
[debug] manifoldjs  : Unable to create the package locally. Invoking the CloudAppX service instead...
[debug] manifoldjs  : Invoking the CloudAppX service...
[error] manifoldjs  : Failed to package the Microsoft Edge Extension Platform app.
                          at C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\manifoldjs-lib\lib\projectBuilder.js:140:29
                          at _rejected (C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:864:24)
                          at C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:890:30
                          at Promise.when (C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:1142:31)
                          at Promise.promise.promiseDispatch (C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:808:41)
                          at C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:624:44
                          at runSingle (C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:137:13)
                          at flush (C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:125:13)
                          at _combinedTickCallback (internal/process/next_tick.js:67:7)
                          at process._tickCallback (internal/process/next_tick.js:98:9)
                      Failed to create the package. The CloudAppX service returned an error - Internal Server Error (500):
                          at Request._callback (C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\manifoldjs-edgeextension\lib\appPackage.js:72:32)
                          at Request.self.callback (C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\request\request.js:185:22)
                          at emitTwo (events.js:106:13)
                          at Request.emit (events.js:191:7)
                          at Request.&lt;anonymous&gt; (C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\request\request.js:1161:10)
                          at emitOne (events.js:96:13)
                          at Request.emit (events.js:188:7)
                          at IncomingMessage.&lt;anonymous&gt; (C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\request\request.js:1083:12)
                          at IncomingMessage.g (events.js:291:16)
                          at emitNone (events.js:91:20)
[error] manifoldjs  : One or more platforms could not be generated successfully.
                          at C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\manifoldjs-lib\lib\projectBuilder.js:28:23
                          at _fulfilled (C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:854:54)
                          at self.promiseDispatch.done (C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:883:30)
                          at Promise.promise.promiseDispatch (C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:816:13)
                          at C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:624:44
                          at runSingle (C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:137:13)
                          at flush (C:\Users\tmnoo\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:125:13)
                          at _combinedTickCallback (internal/process/next_tick.js:67:7)
                          at process._tickCallback (internal/process/next_tick.js:98:9)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40ef92b6-7585-6745-1a00-a518799cf7c9
* Version Independent ID: 736d9322-5206-de84-1da5-b0d6218a7618
* Content: [Extensions - Using ManifoldJS to package extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/packaging/using-manifoldjs-to-package-extensions)
* Content Source: [microsoft-edge/extensions/guides/packaging/using-manifoldjs-to-package-extensions.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/packaging/using-manifoldjs-to-package-extensions.md)
* Product: **microsoft-edge**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by mattwojo** [comment]
Thanks @tmnoonan --- this Extensions content needs some major update work. Getting it scheduled and will update once we've got things corrected.

**Comment by bilalasif** [comment]
was this ever sorted out facing the same issue here

**Comment by tmnoonan** [comment]
I never received an update.  Haven't tried packaging in over a year.

**Comment by gebansal** [comment]
Considering its an old thread and we have rolled out a new Chromium-based Edge browser, I'll go ahead and close it. If you still are facing any issues, please feel free to reopen this issue or file a new one.
