### ISSUE TITLE
Exception error: java.lang.NoClassDefFoundError: net/jodah/failsafe/Policy when executing sample code

### ISSUE THREAD

**Issue by DeZaelez** [MicrosoftDocs/edge-developer#1872]
The sample on this page does not work.  When I try to execute this code using TestNG, I get the following error message

```
java.lang.NoClassDefFoundError: net/jodah/failsafe/Policy
	at org.openqa.selenium.remote.http.ClientConfig.<clinit>(ClientConfig.java:33)
	at org.openqa.selenium.remote.HttpCommandExecutor.<init>(HttpCommandExecutor.java:95)
	at org.openqa.selenium.remote.HttpCommandExecutor.<init>(HttpCommandExecutor.java:85)
	at org.openqa.selenium.remote.HttpCommandExecutor.<init>(HttpCommandExecutor.java:66)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.<init>(DriverCommandExecutor.java:67)
	at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:186)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:180)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:156)
	at xsandbox.EdgeBrowserTest.LaunchBrowser(EdgeBrowserTest.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ClassNotFoundException: net.jodah.failsafe.Policy
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 33 more
```
Is there a known fix for this?
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9fa537-f960-f6f9-a39f-5ea14b41f01f
* Version Independent ID: de9fa537-f960-f6f9-a39f-5ea14b41f01f
* Content: [Use Internet Explorer Driver to automate IE mode in Microsoft Edge - Microsoft Edge Development](https://docs.microsoft.com/en-gb/microsoft-edge/webdriver-chromium/ie-mode?tabs=java#the-complete-sample)
* Content Source: [microsoft-edge/webdriver-chromium/ie-mode.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webdriver-chromium/ie-mode.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by DeZaelez** [comment]
I'm not sure if the comments on that page are meant to be for the documentation alone, or if it is meant to report bugs in the code.  But bottom line is that the code in the example produces an exception error, so either there is a bug with the code, or the documentation is inaccurate.
Thanks for looking into it.

**Comment by captainbrosset** [comment]
Totally agreed, either we need to fix the code, or the docs, but both are maintained on this repository here, so you've reached the right place.

**Comment by bwalderman** [comment]
The code as written (a standalone java app) builds and runs successfully. From a quick search, it looks like this issue might be specific to the maven failsafe plugin: https://stackoverflow.com/questions/70959285/intellij-java-lang-noclassdeffounderror-net-jodah-failsafe-policy

That user has an almost identical issue, but with ChromeDriver. The answer has some links that might be helpful. I wasn't able to repro the exception with a simple TestNG test project, so I'm not able to verify if this will resolve the issue. In any case, since this doesn't appear browser specific, I'd recommend raising this issue at https://github.com/SeleniumHQ/selenium/issues

**Comment by captainbrosset** [comment]
Thank you Brandon. Closing this issue since the code in the documentation seems correct.
