### ISSUE TITLE
System.InvalidCastException thrown when using webview2 winforms - webView.CoreWebView2.Navigate(string)

### ISSUE THREAD

**Issue by jn011** [MicrosoftDocs/edge-developer#697]
## Background information
So happy that the C# side of WebView2 is moving steadily, thank you very much 😃 

I followed the guide here: [https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms](url) 

Everything worked a charm! 

I am now running my webview2 winforms app as a child process and making a call to Navigate in the code below a System.InvalidCastException is thrown.
```c#
public bool WebViewNavigate(string dest)  //"http://localhost:9999" is what dest equals
{
    if (webView != null && webView.CoreWebView2 != null)
    {
        webView.CoreWebView2.Navigate(dest);
        return true;
    }
    return false;
}
```
 
## StackTrace
On this call to CoreWebView2.Navigate the stacktrace below is thrown.

`Application: AV.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidCastException
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(System.Object, IntPtr, IntPtr ByRef, Boolean ByRef)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.WinForms.WebView2.get_CoreWebView2()
   at AV.MainWindow.WebViewNavigate(System.String)
   at AV.MainWindow.StartCall(System.String)
   at AV.MainWindow.MessagingThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
`

Any help/advice is much appreciated 😃

**Comment by Reezaali** [comment]
Hi @jn011, sorry to hear about this problem. This repo is used for documentation issues. To get support from the engineering team, you can log issues here: 
https://github.com/MicrosoftEdge/WebViewFeedback
I'll go ahead and close out this issue now. Thanks.
